name: Build Tsianjery

on:
  push:
    branches:
      - main

jobs:

  hello:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: |
          echo "===================================="
          echo " Hello from Tsianjery Publishing System"
          echo "===================================="
